Capitulo01/Models/Departamento.cs
namespace Capitulo01.Models
{
    public class Departamento
    {
        public long? DepartamentoID { get; set; }
        public string Nome { get; set; }
    }
}

Capitulo01/Models/ErrorViewModel.cs
using System;

namespace Capitulo01.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Capitulo01/Models/Instituicao.cs
namespace Capitulo01.Models
{
    public class Instituicao
    {
        public long? InstituicaoID { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
    }
}

Capitulo01/Controllers/DepartamentoController.cs
using Capitulo01.Data;
using Capitulo01.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Capitulo01.Controllers
{
    public class DepartamentoController : Controller
    {
        private readonly IESContext _context;

        public DepartamentoController(IESContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departamentos.OrderBy(c => c.Nome).ToListAsync());
        }

        // GET: Departamento/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome")] Departamento departamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(departamento);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(nameof(Index));
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var departamento = await _context.Departamentos.SingleOrDefaultAsync(m => m.DepartamentoID == id);

            if (departamento == null)
            {
                return NotFound();
            }
            return View(departamento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("DepartamentoID, Nome")] Departamento departamento)
        {
            if (id != departamento.DepartamentoID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentoExists(departamento.DepartamentoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                   
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departamento);
        }

        private bool DepartamentoExists(long? id)
        {
            return _context.Departamentos.Any(e => e.DepartamentoID == id);
        }
    }
}

Capitulo01/Controllers/HomeController.cs
using Capitulo01.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Capitulo01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Capitulo01/Controllers/InstituicaoController.cs
using Capitulo01.Data;
using Capitulo01.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capitulo01.Controllers
{
    public class InstituicaoController : Controller
    {
        private readonly IESContext _context;

        public InstituicaoController(IESContext context)
        {
            _context = context;
        }

        //private static IList<Instituicao> instituicoes = new List<Instituicao>()
        //{
        //    new Instituicao()   
        //    {
        //        InstituicaoID = 1,
        //        Nome = "UniParaná",
        //        Endereco = "Paraná"
        //    },
        //    new Instituicao()
        //    {
        //        InstituicaoID = 2,
        //        Nome = "UniSanta",
        //        Endereco = "Santa Catarina"
        //    },
        //    new Instituicao()
        //    {
        //        InstituicaoID = 3,
        //        Nome = "UniSãoPaulo",
        //        Endereco = "São	Paulo"
        //    },
        //    new Instituicao()
        //    {
        //        InstituicaoID = 4,
        //        Nome = "UniSulgrandense",
        //        Endereco = "Rio	Grande do Sul"
        //    },
        //    new Instituicao()
        //    {
        //        InstituicaoID = 5,
        //        Nome = "UniCarioca",
        //        Endereco = "Rio	de Janeiro"
        //    }
        //};

        //// GET: Index
        //public IActionResult Index()
        //{
        //    return View(instituicoes.OrderBy(i => i.InstituicaoID));
        //}

        public async Task<IActionResult> Index()
        {
            return View(await _context.Instituicoes.OrderBy(c => c.InstituicaoID).ToListAsync());
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(Instituicao instituicao)
        //{
            
        //    if (instituicoes.Count < 1)
        //    {
        //        instituicao.InstituicaoID = 1;
        //    }
        //    else
        //    {
        //        instituicao.InstituicaoID = instituicoes.Select(i => i.InstituicaoID).Max() + 1;
        //    }
        //    instituicoes.Add(instituicao);

        //    return RedirectToAction(nameof(Index));
        //}

        //public ActionResult Edit(long id)
        //{
        //    return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit (Instituicao instituicao)
        //{
        //    //instituicoes.Remove(instituicoes.Where(i => i.InstituicaoID == instituicao.InstituicaoID).First());
        //    //instituicoes.Add(instituicao);
        //    instituicoes[instituicoes.IndexOf(instituicoes.Where(i => i.InstituicaoID == instituicao.InstituicaoID).First())] = instituicao;
        //    return RedirectToAction(nameof(Index));
        //}

        //public ActionResult Details(int id)
        //{
        //    return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        //}

        //public ActionResult Delete(int id)
        //{
        //    return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(Instituicao instituicao)
        //{
        //    instituicoes.Remove(instituicoes.Where(i => i.InstituicaoID == instituicao.InstituicaoID).First());
        //    return RedirectToAction(nameof(Index));
        //}
    }
}

Capitulo01/Views/Departamento/Create.cshtml
@model Capitulo01.Models.Departamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Capitulo01/Views/Departamento/Edit.cshtml
@model Capitulo01.Models.Departamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DepartamentoID" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Capitulo01/Views/Departamento/Index.cshtml
@model IEnumerable<Capitulo01.Models.Departamento>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<h1 class="card-title align-content-center">Departamentos</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DepartamentoID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DepartamentoID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DepartamentoID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Capitulo01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Capitulo01/Views/Instituicao/Create.cshtml
@model Capitulo01.Models.Instituicao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Instituicao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco" class="form-control" />
                    <span asp-validation-for="Endereco" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Capitulo01/Views/Instituicao/Delete.cshtml
@model Capitulo01.Models.Instituicao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instituicao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InstituicaoID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Capitulo01/Views/Instituicao/Details.cshtml
@model Capitulo01.Models.Instituicao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Instituicao</h4>
    <hr />

    <dl class="row">
        <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.InstituicaoID)
        </dt>
        <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.InstituicaoID)
        </dd>
        <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Endereco)
        </dd>
    </dl>

</div>
<div>
        @Html.ActionLink("Edit", "Edit", new { id = Model.InstituicaoID }) |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Capitulo01/Views/Instituicao/Edit.cshtml
@model Capitulo01.Models.Instituicao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-horizontal">
                <h4>Instituição</h4>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            </div>
            <input type="hidden" asp-for="InstituicaoID" />
            <div class="form-group">
                <label asp-for="Nome" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco" class="form-control" />
                    <span asp-validation-for="Endereco" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</body>
</html>

Capitulo01/Views/Instituicao/Index.cshtml
@model IEnumerable<Capitulo01.Models.Instituicao>

@{
    ViewData["Title"] = "Instituição";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
<h1 class="card-title align-content-center">Instituições</h1>
<p>
    <a asp-action="Create">Criar nova instituição</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InstituicaoID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InstituicaoID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.InstituicaoID }) |
                @Html.ActionLink("Details", "Details", new { id = item.InstituicaoID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.InstituicaoID })
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Capitulo01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capitulo01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instituicao" asp-action="Index">Instituições</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="Index">Departamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Capitulo01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>